### PR TITLE
make it compile again

### PR DESCRIPTION
**Pull request by theScrabi**
Compilation broke, because some of the repos this preoject relies on have moved.

### CODE REVIEW

**Comment by ameuret** [comment]
I've started picking the low-hanging fruits:

 - imagemagick is missing
 - gmp depends on lzip
 - fontconfig has moved to GitLab
 - CGAL branch 5.4.x released. Now tagged v5.4.5

But I'm stuck with a missing dependency on lib3mf... 😢

**Comment by t-paul** [comment]
Stuck on lib3mf means what exactly? OpenSCAD mostly still uses ancient version 1.8.1. Are you trying to move this to v2.2.x?

**Comment by ameuret** [comment]
Thanks for the prompt reply, here's a more comprehensive dump of the failing stage:

```
❯ docker build libs/openscad -f Dockerfile -t openscad --no-cache=true --progress=plain
#0 building with "default" instance using docker driver

#1 [internal] load .dockerignore
#1 transferring context: 2B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 1.66kB done
#2 DONE 0.1s

#3 [internal] load metadata for docker.io/library/openscad-base:latest
#3 DONE 0.0s

#4 [1/9] FROM docker.io/library/openscad-base
#4 CACHED

#5 [internal] load build context
#5 transferring context: 249.55kB 0.1s done
#5 DONE 0.2s

#6 [2/9] COPY . .
#6 DONE 2.3s

#7 [3/9] RUN pwd
#7 0.310 /src
#7 DONE 0.3s

#8 [4/9] RUN export PKG_CONFIG_PATH="/emsdk/upstream/emscripten/cache/sysroot/lib/pkgconfig" &&     emcmake cmake -B ../build .     -DWASM=ON     -DSNAPSHOT=ON     -DEXPERIMENTAL=ON     -DENABLE_CAIRO=OFF     -DUSE_MIMALLOC=OFF     -DBoost_USE_STATIC_RUNTIME=ON     -DBoost_USE_STATIC_LIBS=ON     -DCMAKE_BUILD_TYPE=Release     -DHARFBUZZ_INCLUDE_DIRS=/emsdk/upstream/emscripten/cache/sysroot/include/harfbuzz     -DFONTCONFIG_INCLUDE_DIR=/emsdk/upstream/emscripten/cache/sysroot/include/fontconfig     -DFONTCONFIG_LIBRARIES=libfontconfig.a
#8 0.455 configure: cmake -B ../build . -DWASM=ON -DSNAPSHOT=ON -DEXPERIMENTAL=ON -DENABLE_CAIRO=OFF -DUSE_MIMALLOC=OFF -DBoost_USE_STATIC_RUNTIME=ON -DBoost_USE_STATIC_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DHARFBUZZ_INCLUDE_DIRS=/emsdk/upstream/emscripten/cache/sysroot/include/harfbuzz -DFONTCONFIG_INCLUDE_DIR=/emsdk/upstream/emscripten/cache/sysroot/include/fontconfig -DFONTCONFIG_LIBRARIES=libfontconfig.a -DCMAKE_TOOLCHAIN_FILE=/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/emsdk/node/16.20.0_64bit/bin/node
#8 0.465 CMake Deprecation Warning at CMakeLists.txt:16 (cmake_policy):
#8 0.465   The OLD behavior for policy CMP0071 will be removed from a future version
#8 0.465   of CMake.
#8 0.465
#8 0.465   The cmake-policies(7) manual explains that the OLD behaviors of all
#8 0.465   policies are deprecated and that a policy should be set to OLD only under
#8 0.465   specific short-term circumstances.  Projects should be ported to the NEW
#8 0.465   behavior and not rely on setting a policy to OLD.
#8 0.465
#8 0.465
#8 0.955 -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2")
#8 0.961 -- Eigen3: 3.3.90
#8 0.973 -- Found Boost: /emsdk/upstream/emscripten/cache/sysroot/lib/cmake/Boost-1.84.0/BoostConfig.cmake (found suitable version "1.84.0", minimum required is "1.36") found components: filesystem system regex program_options
#8 0.975 -- Boost: 1.84.0
#8 0.985 -- Harfbuzz:
#8 0.986 -- Fontconfig:
#8 0.986 -- running openscad/cmake/Modules/FindGLIB2.cmake ...
#8 0.986 -- saving pkg-config env
#8 0.991 -- Checking for one of the modules 'glib-2.0'
#8 0.994 CMake Error at /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:890 (message):
#8 0.994   None of the required 'glib-2.0' found
#8 0.994 Call Stack (most recent call first):
#8 0.994   cmake/Modules/FindGLIB2.cmake:23 (pkg_search_module)
#8 0.994   CMakeLists.txt:291 (find_package)
#8 0.994
#8 0.995 -- GLIB2_VERSION
#8 0.995 -- GLIB2_LIBRARY_DIRS
#8 0.995 -- GLIB2_INCLUDE_DIRS:
#8 0.995 -- GLIB2_LIBDIR
#8 0.995
#8 0.995 -- GLIB2_LIBRARIES:
#8 0.995 -- restoring pkg-config env
#8 0.995 -- Glib:
#8 1.000 -- Using header-only CGAL
#8 1.002 -- Targetting Unix Makefiles
#8 1.002 -- Using /emsdk/upstream/emscripten/em++ compiler.
#8 1.004 -- Found GMP: /emsdk/upstream/emscripten/cache/sysroot/lib/libgmp.a
#8 1.006 -- Found MPFR: /emsdk/upstream/emscripten/cache/sysroot/lib/libmpfr.a
#8 1.013 -- Found Boost: /emsdk/upstream/emscripten/cache/sysroot/lib/cmake/Boost-1.84.0/BoostConfig.cmake (found suitable version "1.84.0", minimum required is "1.48")
#8 1.013 -- Boost include dirs: /emsdk/upstream/emscripten/cache/sysroot/include
#8 1.013 -- Boost libraries:
#8 1.015 -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
#8 2.108 -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
#8 2.111 -- Found Threads: TRUE
#8 2.112 -- CGAL: 5.4
#8 2.112 -- CGAL: Using target CGAL::CGAL CGAL::CGAL_Core
#8 2.162 -- libzip: 1.10.1
#8 2.170 -- Freetype: 2.13.2
#8 2.222 -- LibXml2: 2.12.0
#8 2.234 -- HIDAPI: disabled
#8 2.237 -- SpNav: disabled
#8 2.237 -- Cairo: disabled per user request
#8 2.242 -- Flex: 2.6.4
#8 2.246 -- Bison: 3.8.2
#8 2.251 -- Checking for module 'lib3MF'
#8 2.254 --   No package 'lib3MF' found
#8 2.255 -- Checking for module 'lib3mf'
#8 2.257 --   No package 'lib3mf' found
#8 2.259 -- lib3mf: disabled
#8 2.260 -- Offscreen OpenGL Context - using NULLGL
#8 2.261 -- NULLGL is set. Overriding OpenGL(TM) settings
#8 2.262 --
#8 2.262 -- ====================================
#8 2.262 -- OpenSCAD Build Configuration Summary
#8 2.262 -- ====================================
#8 2.262 --
#8 2.262 -- CMAKE_VERSION:         3.22.1
#8 2.262 -- CMAKE_TOOLCHAIN_FILE:  /emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
#8 2.262 -- CMAKE_GENERATOR:       Unix Makefiles
#8 2.262 -- CPACK_CMAKE_GENERATOR:
#8 2.262 -- CMAKE_BUILD_TYPE:      Release
#8 2.262 -- CMAKE_PREFIX_PATH:
#8 2.262 -- SUFFIX:
#8 2.262 --
#8 2.262 -- Experimental Features: ON
#8 2.262 -- Snapshot build:        ON
#8 2.262 -- Headless build:        ON
#8 2.262 -- NULLGL build:          ON
#8 2.262 -- Profiling/coverage:    OFF
#8 2.262 -- Use mimalloc:          OFF
#8 2.262 -- CSG node id-prefix:    OFF
#8 2.262 -- Offline documentation: OFF
#8 2.262 --
#8 2.262 -- GL Offscreen Context:  NULLGL
#8 2.262 -- lib3mf:                disabled
#8 2.262 --
#8 2.262 -- Input Drivers
#8 2.262 -- - HID API Driver (disabled)
#8 2.262 -- - Space Navigator Library Driver (disabled)
#8 2.263 -- - Joystick Driver (disabled)
#8 2.263 -- - DBus Remote Driver (disabled)
#8 2.263 --
#8 2.263 -- DEFINES = CGAL_DISABLE_ROUNDING_MATH_CHECK;USE_WASM_COMPATIBLE_KERNELS;ENABLE_EXPERIMENTAL;_REENTRANT;UNICODE;_UNICODE;STACKSIZE=8388608;EIGEN_DONT_ALIGN;NULLGL;ENABLE_CGAL;CGAL_DEBUG;CGAL_USE_GMPXX;ENABLE_LIBZIP;OPENSCAD_VERSION=2023.09.08;OPENSCAD_SHORTVERSION=2023.09.08;OPENSCAD_YEAR=2023;OPENSCAD_MONTH=9;OPENSCAD_DAY=8;OPENSCAD_OS="Unix";OPENSCAD_NOGUI;OPENSCAD_SNAPSHOT
#8 2.263 --
#8 2.272 -- Could NOT find ImageMagick (missing: ImageMagick_convert_EXECUTABLE ImageMagick_convert_EXECUTABLE)
#8 2.273 -- Couldn't find imagemagick 'convert' program
#8 2.273 -- using diffpng for image comparison
#8 2.289 -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.10.12", minimum required is "3.4")
#8 2.294 -- Checking for module 'lib3MF'
#8 2.297 --   No package 'lib3MF' found
#8 2.322 -- creating CTestCustom.cmake
#8 4.037 -- Configuring incomplete, errors occurred!
#8 4.037 See also "/build/CMakeFiles/CMakeOutput.log".
#8 4.045 emcmake: error: 'cmake -B ../build . -DWASM=ON -DSNAPSHOT=ON -DEXPERIMENTAL=ON -DENABLE_CAIRO=OFF -DUSE_MIMALLOC=OFF -DBoost_USE_STATIC_RUNTIME=ON -DBoost_USE_STATIC_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DHARFBUZZ_INCLUDE_DIRS=/emsdk/upstream/emscripten/cache/sysroot/include/harfbuzz -DFONTCONFIG_INCLUDE_DIR=/emsdk/upstream/emscripten/cache/sysroot/include/fontconfig -DFONTCONFIG_LIBRARIES=libfontconfig.a -DCMAKE_TOOLCHAIN_FILE=/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/emsdk/node/16.20.0_64bit/bin/node' failed (returned 1)
#8 ERROR: process "/bin/sh -c export PKG_CONFIG_PATH=\"/emsdk/upstream/emscripten/cache/sysroot/lib/pkgconfig\" &&     emcmake cmake -B ../build .     -DWASM=ON     -DSNAPSHOT=ON     -DEXPERIMENTAL=ON     -DENABLE_CAIRO=OFF     -DUSE_MIMALLOC=OFF     -DBoost_USE_STATIC_RUNTIME=ON     -DBoost_USE_STATIC_LIBS=ON     -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}     -DHARFBUZZ_INCLUDE_DIRS=/emsdk/upstream/emscripten/cache/sysroot/include/harfbuzz     -DFONTCONFIG_INCLUDE_DIR=/emsdk/upstream/emscripten/cache/sysroot/include/fontconfig     -DFONTCONFIG_LIBRARIES=libfontconfig.a" did not complete successfully: exit code: 1
------
 > [4/9] RUN export PKG_CONFIG_PATH="/emsdk/upstream/emscripten/cache/sysroot/lib/pkgconfig" &&     emcmake cmake -B ../build .     -DWASM=ON     -DSNAPSHOT=ON     -DEXPERIMENTAL=ON     -DENABLE_CAIRO=OFF     -DUSE_MIMALLOC=OFF     -DBoost_USE_STATIC_RUNTIME=ON     -DBoost_USE_STATIC_LIBS=ON     -DCMAKE_BUILD_TYPE=Release     -DHARFBUZZ_INCLUDE_DIRS=/emsdk/upstream/emscripten/cache/sysroot/include/harfbuzz     -DFONTCONFIG_INCLUDE_DIR=/emsdk/upstream/emscripten/cache/sysroot/include/fontconfig     -DFONTCONFIG_LIBRARIES=libfontconfig.a:
2.272 -- Could NOT find ImageMagick (missing: ImageMagick_convert_EXECUTABLE ImageMagick_convert_EXECUTABLE)
2.273 -- Couldn't find imagemagick 'convert' program
2.273 -- using diffpng for image comparison
2.289 -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.10.12", minimum required is "3.4")
2.294 -- Checking for module 'lib3MF'
2.297 --   No package 'lib3MF' found
2.322 -- creating CTestCustom.cmake
4.037 -- Configuring incomplete, errors occurred!
4.037 See also "/build/CMakeFiles/CMakeOutput.log".
4.045 emcmake: error: 'cmake -B ../build . -DWASM=ON -DSNAPSHOT=ON -DEXPERIMENTAL=ON -DENABLE_CAIRO=OFF -DUSE_MIMALLOC=OFF -DBoost_USE_STATIC_RUNTIME=ON -DBoost_USE_STATIC_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DHARFBUZZ_INCLUDE_DIRS=/emsdk/upstream/emscripten/cache/sysroot/include/harfbuzz -DFONTCONFIG_INCLUDE_DIR=/emsdk/upstream/emscripten/cache/sysroot/include/fontconfig -DFONTCONFIG_LIBRARIES=libfontconfig.a -DCMAKE_TOOLCHAIN_FILE=/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/emsdk/node/16.20.0_64bit/bin/node' failed (returned 1)
------
Dockerfile:8
--------------------
   7 |     RUN pwd
   8 | >>> RUN export PKG_CONFIG_PATH="/emsdk/upstream/emscripten/cache/sysroot/lib/pkgconfig" && \
   9 | >>>     emcmake cmake -B ../build . \
  10 | >>>     -DWASM=ON \
  11 | >>>     -DSNAPSHOT=ON \
  12 | >>>     -DEXPERIMENTAL=ON \
  13 | >>>     -DENABLE_CAIRO=OFF \
  14 | >>>     -DUSE_MIMALLOC=OFF \
  15 | >>>     -DBoost_USE_STATIC_RUNTIME=ON \
  16 | >>>     -DBoost_USE_STATIC_LIBS=ON \
  17 | >>>     -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} \
  18 | >>>     -DHARFBUZZ_INCLUDE_DIRS=/emsdk/upstream/emscripten/cache/sysroot/include/harfbuzz \
  19 | >>>     -DFONTCONFIG_INCLUDE_DIR=/emsdk/upstream/emscripten/cache/sysroot/include/fontconfig \
  20 | >>>     -DFONTCONFIG_LIBRARIES=libfontconfig.a
  21 |
--------------------
ERROR: failed to solve: process "/bin/sh -c export PKG_CONFIG_PATH=\"/emsdk/upstream/emscripten/cache/sysroot/lib/pkgconfig\" &&     emcmake cmake -B ../build .     -DWASM=ON     -DSNAPSHOT=ON     -DEXPERIMENTAL=ON     -DENABLE_CAIRO=OFF     -DUSE_MIMALLOC=OFF     -DBoost_USE_STATIC_RUNTIME=ON     -DBoost_USE_STATIC_LIBS=ON     -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}     -DHARFBUZZ_INCLUDE_DIRS=/emsdk/upstream/emscripten/cache/sysroot/include/harfbuzz     -DFONTCONFIG_INCLUDE_DIR=/emsdk/upstream/emscripten/cache/sysroot/include/fontconfig     -DFONTCONFIG_LIBRARIES=libfontconfig.a" did not complete successfully: exit code: 1

```

I've distanced myself from docker for a few years now and am not familiar with the _new_ building process. How do I get inside the failing container, when I run a shell to the latest container, it doesn't look like it's where the process just stopped. And I have not much time to invest in getting up to date.

**Comment by t-paul** [comment]
Right, so this is unrelated to this issue. FWIW, I've successfully rebuilt with CGAL 5.6, the fontconfig change from the original post and updated gist https://gist.github.com/kleisauke/acfa1c09522705efa5eb0541d2d00887 (for new zlib version).

@DSchroer what do you think about moving the repo into the OpenSCAD org for sharing the load on updating?

As for the build issue, you likely need https://github.com/openscad/openscad/blob/master/.circleci/config.yml#L126C1-L126C94 so `cmake` can find `lib3mf`.

**Comment by DSchroer** [comment]
I am happy to move this into OpenSCAD. I have been updating the libraries every so often but the work isnt high on my priority list. @t-paul how do you want to do the migration?

**Comment by t-paul** [comment]
@DSchroer I think the easiest way is that I'll invite you to OpenSCAD, you as owner should then get the transfer button somewhere in settings.

**Comment by DSchroer** [comment]
@t-paul sounds good. Ill try to get that done soon if not by end of the weekend.

**Comment by DSchroer** [comment]
@t-paul got the invite. Just need the correct permissions before I can do the transfer. Currently it is marked as insufficient.

**Comment by t-paul** [comment]
Oh, I think it's actually that:
> The target account must not have a repository with the same name, or a fork in the same network.

Let me rename that fork...

**Comment by t-paul** [comment]
I've renamed the fork, I hope the redirect does not conflict. I guess if everything else fails, I'll just drop our fork after making another local copy.

**Comment by DSchroer** [comment]
@t-paul still no luck. Insufficient permission

**Comment by t-paul** [comment]
If it still does not work, I need a huge coffee for reading through all the github documentation :-).

**Comment by DSchroer** [comment]
@t-paul Done. Feel free to lower my permissions in the org if you want.

**Comment by t-paul** [comment]
Whew, that worked. I made you admin of the repo so you should continue to have pretty much all permissions.

**Comment by DSchroer** [comment]
Awesome. Thanks for the help :)

**Comment by t-paul** [comment]
Sorry everyone registered on this issue. To make it worth it, lets merge this. I'll update to CGAL 5.6 (confirmed building the WASM image, not surprising as it's header-only) once I verified the actual OpenSCAD build works too.

**Pull request merged**
